# .goreleaser.yaml
version: 2
project_name: npm-security-auditter

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/auditter
    binary: auditter
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      auditter_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - CONTRIBUTING.md
      - SECURITY.md

# Linux packages (DEB, RPM, APK, Arch)
nfpms:
  - id: packages
    package_name: auditter
    vendor: npm-security-auditter
    homepage: https://github.com/kluth/npm-security-auditter
    maintainer: Matthias Kluth <matthias@kluth.dev>
    description: Security auditing tool for npm packages - analyzes tarball contents, network behavior, and sandbox execution
    license: MIT
    formats:
      - deb
      - rpm
      - apk
      - archlinux
    bindir: /usr/bin
    section: utils
    priority: optional
    contents:
      - src: ./README.md
        dst: /usr/share/doc/auditter/README.md
      - src: ./LICENSE
        dst: /usr/share/doc/auditter/LICENSE
    rpm:
      group: Development/Tools
    deb:
      lintian_overrides:
        - statically-linked-binary

# macOS universal binary
universal_binaries:
  - replace: true

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

# Create GitHub release
release:
  github:
    owner: kluth
    name: npm-security-auditter
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
  header: |
    ## NPM Security Auditter v{{.Version}}

    ### Installation

    **macOS (PKG installer):**
    Download `auditter_v{{.Version}}_macOS_Universal.pkg` from assets below.

    **macOS (Homebrew - manual):**
    ```bash
    brew install --cask ./auditter_{{.Version}}_darwin_arm64.tar.gz
    ```

    **Linux (DEB - Debian/Ubuntu):**
    ```bash
    sudo dpkg -i auditter_{{.Version}}_linux_amd64.deb
    ```

    **Linux (RPM - Fedora/RHEL):**
    ```bash
    sudo rpm -i auditter_{{.Version}}_linux_amd64.rpm
    ```

    **Linux (APK - Alpine):**
    ```bash
    sudo apk add --allow-untrusted auditter_{{.Version}}_linux_amd64.apk
    ```

    **Linux (Arch):**
    ```bash
    sudo pacman -U auditter_{{.Version}}_linux_amd64.pkg.tar.zst
    ```

    **Windows (Installer):**
    Download `auditter_v{{.Version}}_windows_amd64_installer.exe` from assets below.

    **Windows (Manual):**
    Download `npm-security-auditter_{{.Version}}_windows_amd64.zip` and add to PATH.

    **Manual download:** See assets below for your platform.

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
  groups:
    - title: 'Features'
      regexp: '^feat'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^fix'
      order: 1
    - title: 'Security'
      regexp: '^sec'
      order: 2
    - title: 'Dependencies'
      regexp: '^deps'
      order: 3
    - title: 'Other'
      order: 999
