# .goreleaser.yaml
version: 2
project_name: npm-security-auditter

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/auditter
    binary: auditter
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - CONTRIBUTING.md
      - SECURITY.md

# Linux packages (DEB, RPM, APK)
nfpms:
  - id: packages
    package_name: auditter
    vendor: npm-security-auditter
    homepage: https://github.com/kluth/npm-security-auditter
    maintainer: Matthias Kluth <matthias@kluth.dev>
    description: Security auditing tool for npm packages - analyzes tarball contents, network behavior, and sandbox execution
    license: MIT
    formats:
      - deb
      - rpm
      - apk
      - archlinux
    bindir: /usr/bin
    section: utils
    priority: optional
    contents:
      - src: ./README.md
        dst: /usr/share/doc/auditter/README.md
      - src: ./LICENSE
        dst: /usr/share/doc/auditter/LICENSE
    rpm:
      group: Development/Tools
    deb:
      lintian_overrides:
        - statically-linked-binary

# Homebrew tap for macOS/Linux
brews:
  - name: auditter
    repository:
      owner: kluth
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: https://github.com/kluth/npm-security-auditter
    description: Security auditing tool for npm packages
    license: MIT
    install: |
      bin.install "auditter"
    test: |
      system "#{bin}/auditter", "--version"

# Windows Scoop manifest
scoops:
  - name: auditter
    repository:
      owner: kluth
      name: scoop-bucket
      token: "{{ .Env.SCOOP_BUCKET_TOKEN }}"
    homepage: https://github.com/kluth/npm-security-auditter
    description: Security auditing tool for npm packages
    license: MIT

# Windows Chocolatey package
chocolateys:
  - name: auditter
    owners: kluth
    title: NPM Security Auditter
    authors: Matthias Kluth
    project_url: https://github.com/kluth/npm-security-auditter
    license_url: https://github.com/kluth/npm-security-auditter/blob/main/LICENSE
    require_license_acceptance: false
    project_source_url: https://github.com/kluth/npm-security-auditter
    docs_url: https://github.com/kluth/npm-security-auditter#readme
    bug_tracker_url: https://github.com/kluth/npm-security-auditter/issues
    tags: "npm security audit packages cli"
    summary: Security auditing tool for npm packages
    description: |
      NPM Security Auditter analyzes npm packages for security issues including:
      - Tarball content analysis
      - Dynamic sandbox execution
      - Network behavior monitoring
      - Suspicious pattern detection
    release_notes: "https://github.com/kluth/npm-security-auditter/releases/tag/v{{ .Version }}"
    api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"
    source_repo: "https://push.chocolatey.org/"
    skip_publish: false

# Universal binaries for macOS
universal_binaries:
  - replace: true

# macOS DMG installer
dmg:
  - id: macos-dmg
    ids:
      - npm-security-auditter
    name_template: "{{ .ProjectName }}_{{ .Version }}_macOS_Universal"
    replace: true

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

# Sign macOS binaries (if configured)
signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

# Create GitHub release
release:
  github:
    owner: kluth
    name: npm-security-auditter
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
  header: |
    ## NPM Security Auditter v{{.Version}}

    ### Installation

    **macOS (Homebrew):**
    ```bash
    brew install kluth/tap/auditter
    ```

    **Linux (DEB):**
    ```bash
    sudo dpkg -i auditter_{{.Version}}_linux_amd64.deb
    ```

    **Linux (RPM):**
    ```bash
    sudo rpm -i auditter_{{.Version}}_linux_amd64.rpm
    ```

    **Windows (Scoop):**
    ```powershell
    scoop bucket add kluth https://github.com/kluth/scoop-bucket
    scoop install auditter
    ```

    **Windows (Chocolatey):**
    ```powershell
    choco install auditter
    ```

    **Manual download:** See assets below for your platform.

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
  groups:
    - title: '🚀 Features'
      regexp: '^feat'
      order: 0
    - title: '🐛 Bug Fixes'
      regexp: '^fix'
      order: 1
    - title: '🔒 Security'
      regexp: '^sec'
      order: 2
    - title: '📦 Dependencies'
      regexp: '^deps'
      order: 3
    - title: 'Other'
      order: 999
